# Generated by Django 3.0.9 on 2022-02-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='شناسه')),
                ('course_name', models.CharField(max_length=40, verbose_name='نام')),
                ('max_numb_students', models.CharField(max_length=100, verbose_name='ظرفیت دانشجو')),
            ],
            options={
                'verbose_name_plural': 'واحد های درسی',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('dept_name', models.CharField(max_length=50, verbose_name='نام دانشکده')),
                ('courses', models.ManyToManyField(to='ttgen.Course', verbose_name='دروس دانشکده')),
            ],
            options={
                'verbose_name_plural': 'دانشکده',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('name', models.CharField(max_length=25, verbose_name='نام')),
            ],
            options={
                'verbose_name_plural': 'اساتید',
            },
        ),
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='شناسه')),
                ('time', models.CharField(max_length=50, verbose_name='ساعت')),
                ('day', models.CharField(max_length=15, verbose_name='زمان')),
            ],
            options={
                'verbose_name_plural': 'ساعت ها',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('seating_capacity', models.IntegerField(verbose_name='ظرفیت کلاس')),
            ],
            options={
                'verbose_name_plural': 'کلاس ها',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('num_class_in_week', models.IntegerField(verbose_name='تعداد کلاس در هفته')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttgen.Course', verbose_name='نام درس')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.Department', verbose_name='نام دانشکده')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttgen.Instructor', verbose_name='استاد')),
                ('meeting_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttgen.MeetingTime', verbose_name='ساعت درس')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttgen.Room', verbose_name='کلاس')),
            ],
            options={
                'verbose_name_plural': 'گروه های درسی',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(to='ttgen.Instructor', verbose_name='نام مدرسان'),
        ),
    ]
